language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python --version

install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - coverage run -m unittest discover -s .

after_success:
  - codecov
